import aiosqlite
from pathlib import Path
from .config import config

_SCHEMA = Path(__file__).parent.parent / "db" / "schema.sql"
_SEED   = Path(__file__).parent.parent / "db" / "seed.sql"
# Phase-B "haystack" bulk volume (generated by db/gen_seed.py). Loaded AFTER the
# fixture core so the answer-key's exact ids are never disturbed. Optional.
_BULK   = Path(__file__).parent.parent / "db" / "seed_bulk.sql"


async def init_db() -> None:
    """Create and seed the SQLite DB when it isn't already initialized.

    'Initialized' means the core `users` table exists - NOT merely that the file
    is present. This treats an absent file, a 0-byte leftover, or any DB missing
    the schema as a first run, so a stray empty vulnforge.db can't silently
    disable seeding (which otherwise surfaces as 'invalid_credentials' on the
    seeded accounts). Note: this does NOT migrate an existing OLD schema - after
    a schema change you must still delete vulnforge.db to reseed.
    """
    async with aiosqlite.connect(config.DB_PATH) as conn:
        async with conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'users'"
        ) as cur:
            initialized = await cur.fetchone() is not None
        if not initialized:
            await conn.executescript(_SCHEMA.read_text(encoding="utf-8"))
            await conn.executescript(_SEED.read_text(encoding="utf-8"))
            if _BULK.exists():
                await conn.executescript(_BULK.read_text(encoding="utf-8"))
            await conn.commit()


async def get_db():
    """FastAPI dependency - yields one aiosqlite connection per request."""
    async with aiosqlite.connect(config.DB_PATH) as conn:
        conn.row_factory = aiosqlite.Row
        await conn.execute("PRAGMA foreign_keys = ON")
        # Wait (don't error) on a busy write lock - needed when concurrent
        # requests hit the same row (see the race-condition surface).
        await conn.execute("PRAGMA busy_timeout = 5000")
        yield conn
